Do not add DAVIX_DEFINITIONS to Davix::Davix imported target
pkg-config --cflags davix gives:
-D_FILE_OFFSET_BITS=64 -I/usr/include/davix

However, actually adding -D_FILE_OFFSET_BITS=64 to the compilation
breaks the 32bit build, due to mismatches between long and Long64_t:

TDavixFile.cxx:791: undefined reference to
  `Davix::DavPosix::pread(Davix_fd*, void*, unsigned int, long long, Davix::DavixError**)'

while nm libdavix.so shows:
   Davix::DavPosix::pread(Davix_fd*, void*, unsigned int, long, Davix::DavixError**)

which means that offsets are not 64 bits, but 32 bits.