[vmc] Re-apply: Disambiguate ROOT's ::Info from Pythia8's Info:
Some Pythia8 headers expose an unfortunate "using namespace Pythia8".
This triggers:
In file included from /root/ship-log-keep/sw/slc7_x86-64/ROOT/master_FAIRSHIP-1/include/TMCManager.h:26:
/root/ship-log-keep/sw/slc7_x86-64/ROOT/master_FAIRSHIP-1/include/TMCParticleStatus.h:81:7: error: reference to 'Info' is ambiguous
      Info("Print", "Status of track");
      ^
/root/ship-log-keep/sw/BUILD/b61305e07edfb1f9a906335e2093ac409db3c4cc/ROOT/include/TError.h:58:13: note: candidate found by name lookup is 'Info'
extern void Info(const char *location, const char *msgfmt, ...)
            ^
/root/ship-log-keep/sw/slc7_x86-64/pythia/v8230-ship-1/include/Pythia8/Info.h:30:7: note: candidate found by name lookup is 'Pythia8::Info'
class Info {
      ^

By explicitly requesting "::Info" that ambiguity should be resolved.

(cherry picked from commit 91f8b55e51d79487b871c9f5d8e4cbe5a91ba7c1)
(got reverted by commit 86daf6fb6e14f3f4a894140ba38fe7c7a0f2784c)