[df] Ensure proper graph dependencies for local info in distributed mode
In distributed RDataFrame, transformation operations (such as Define)
from which other parts of the API depend upon (such as GetColumnNames or
GetColumnType) are executed not only in the distributed tasks but also
locally, to ensure those other functions can be called. Before this
commit, this was done by simply appending the call to the local
RDataFrame instance attached to the head node. This behaviour was
limited, for example in case the same column name was used in two
separate branches of the computation graph, one could see errors such
as:
```
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3cuda/Tue/x86_64-el8-gcc11-opt/lib/DistRDF/Proxy.py", line 275, in get_proxy_for
    _update_internal_df_with_transformation(node, operation)
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3cuda/Tue/x86_64-el8-gcc11-opt/lib/DistRDF/Proxy.py", line 63, in _update_internal_df_with_transformation
    node.get_head()._localdf = rdf_operation(*operation.args, **operation.kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3cuda/Tue/x86_64-el8-gcc11-opt/lib/ROOT/_pythonization/_rdf_pyz.py", line 394, in _PyDefine
    return rdf._OriginalDefine(col_name, callable_or_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(string_view name, string_view expression) =>
    runtime_error: RDataFrame::Define: cannot define column "nj4". A column with that name has already been Define'd. Use Redefine to force redefinition.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(string_view name, string_view expression) =>
    runtime_error: RDataFrame::Define: cannot define column "nj4". A column with that name has already been Define'd. Use Redefine to force redefinition.
  Failed to instantiate "Define(ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>&,std::string,std::string)"
  Failed to instantiate "Define(ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>*,std::string,std::string)"
  Failed to instantiate "Define(ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>,std::string,std::string)"
```

With this commit, the order of node creation in the computation graph is
respected and transformations are chained to the correct parent node.

This improvement highlighted some minor issues in unittests, which are
now improved as well. A new test for this specific issue has also been
added.

(cherry picked from commit 945a3c122441b53db52354ab5e2602de8643da2f)