[DF][Win] Fix compiler error C3493
Fix the following compiler error on WIndows:
```
dataframe_nodes.cxx(86,40): error C3493: 'N' cannot be implicitly captured because no default capture mode has been specified
```