Fix a compilation error on Win64
Fix the following compilation error on Win64:
```
ReadSpeed.cxx(334,89): error C2398: Element '1': conversion from 'unsigned __int64' to 'T' requires a narrowing conversion
```