Use non-const iterator for TVec::erase()
The interface switched from iterator to const_iterator in C++11,
but GCC 4.8 still uses the old interface and breaks with the error
below if const_iterator is used:

error: no matching function for call to
  ‘std::vector<char, std::allocator<char> >::erase(TVec<char>::const_iterator&)’
   iterator erase(const_iterator pos) { return fData.erase(pos); }
                                                           ^