Fix compilation error with Visual C++ 12 (2013) in Release mode
- Turn optimizations off for g__cfunc.c, otherwise we get a compilation error with Visual C++ 12 (2013) in Release mode (due to the /O2 flag):
g__cfunc.c(835) : error C2099: initializer is not a constant