Add a couple of missing #includes
This fixes the following compilation errors on Windows:
TGeoTessellated.cxx(385,67): error C2027: use of undefined type 'std::array<CellVec_t,1000000>'

And on MacOS:
TGeoTessellated.cxx:385:23: error: implicit instantiation of undefined template 'std::__1::array<std::__1::vector<int, std::__1::allocator<int> >, 1000000>'
      auto grid = new std::array<CellVec_t, ngrid * ngrid * ngrid>;
                      ^