[asan] Fix asan configuration for MacOS
The `c++ --print-file-name` command now seems to work, and it is indeed the more appropriate way to get the location of the asan shared library on MacOS.

Also fix the following problems occurring when building on MacOS with -Dasan=ON

Error:
```
CMake Error at cmake/modules/CheckAtomic.cmake:59 (message):
  Host compiler appears to require libatomic, but cannot find it.
```
Fix: fix typos in asan symbols (extra `_`) and specify correct linker flag (-U)

Error:
```
error: static AddressSanitizer runtime is not supported on darwin
```
Fix: remove `-static-libsan` flag. This is required by latest MacOS Xcode