[PyROOT] Improve error handling for AsNumpy with unreadable objects
Improve the error message when you try to build NumPy arrays with types
that the interpreter doesn't know about.

Running the reproducer from the JIRA ticket, one now gets this output:
```txt
TClass::Init:0: RuntimeWarning: no dictionary for class Foo is available
{ "a", "b", "foo", "foo.a", "foo.b" }
Traceback (most recent call last):
  File "/home/rembserj/root-support/jira/ROOT-10930/reproducer.py", line 13, in <module>
    print(df.AsNumpy())
          ^^^^^^^^^^^^
  File "/home/rembserj/spaces/master/install/lib/root/ROOT/_pythonization/_rdataframe.py", line 243, in RDataFrameAsNumpy
    raise RuntimeError(
RuntimeError: The column named "foo" is of type "Foo", which is not known to the ROOT interpreter. Please load the corresponding header files or dictionaries.
```

This was the output before:
```txt
TClass::Init:0: RuntimeWarning: no dictionary for class Foo is available
{ "a", "b", "foo", "foo.a", "foo.b" }
Traceback (most recent call last):
  File "/home/rembserj/root-support/jira/ROOT-10930/reproducer.py", line 5, in <module>
    print(df.AsNumpy())
          ^^^^^^^^^^^^
  File "/home/rembserj/spaces/master/install/lib/root/ROOT/_pythonization/_rdataframe.py", line 236, in RDataFrameAsNumpy
    result_ptrs[column] = df.Take[column_type](column)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Could not find "Take<Foo>" (set cppyy.set_debug() for C++ errors):
  Failed to instantiate "Take<Foo>(std::string)"
```

Closes the following Jira issue:
https://its.cern.ch/jira/browse/ROOT-10930