interpreter/CMakeLists.txt: correct CLANG_INCLUDE_DIRS
This looks like a regression from https://github.com/root-project/root/commit/56f3b2afe04a7195355350e1b134505de30c8b7d#diff-93558e500b17901f800fbb40a2c2fdfd6ee229077db63413bd4a91ee7ec66ea7. It seems like interpreter/llvm-project/llvm/tools/clang would not be a thing, while a following compilation error is observed:

    In file included from interpreter/cling/lib/Utils/AST.cpp:12:
    In file included from interpreter/llvm-project/clang/include/clang/AST/ASTContext.h:18:
    interpreter/llvm-project/clang/include/clang/AST/ASTFwd.h:21:10: fatal error: 'clang/AST/DeclNodes.inc' file not found
    #include "clang/AST/DeclNodes.inc"
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.