Forgot to link against libXrdSys.a which caused: dyld: Symbol not found: __Z10Swap_n2hlly on MacOS X Intel (issue 22597).
git-svn-id: http://root.cern.ch/svn/root/branches/v5-14-00-patches@17369 27541ba8-7e3a-0410-8455-c3a389f83636