Fix compilation error on Windows
Fix the compilation error C3493: 'everyN' cannot be implicitly captured because no default capture mode has been specified