[cxxmodules] Add bits/unique_ptr to the modulemap to untie module dependency.
The std.condition_variable module can be exported via the std.condition_variable
module or std.memory. On some platforms (gcc10) that causes definition mismatch
problems of kind:

In module 'std' imported from input_line_1:1:
  c++/10.3.0/bits/unique_ptr.h:208:12: error: 'std::__uniq_ptr_data<std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >, std::default_delete<std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > > >, true, true>' has different definitions in different modules; definition in module 'std.condition_variable' is here
     struct __uniq_ptr_data : __uniq_ptr_impl<_Tp, _Dp>
           ^
/c++/10.3.0/bits/unique_ptr.h:208:12: note: definition in module 'std.condition_variable' is here

Try fixing cms-sw/cmssw#36700