Add missing header search path
Fix the potential following compilation error with CMake:
/build/git/master/core/meta/src/TCling.cxx:72:19: fatal error: TFile.h: No such file or directory
 #include "TFile.h"
                   ^
compilation terminated.
make[2]: *** [core/meta/CMakeFiles/MetaLLVM.dir/src/TCling.cxx.o] Error 1