Fix several issues on Windows in core/base
- Force using Visual Studio 2017 or higher
- Undefine unsupported __attribute__ keyword
- Move the TObject constructors from the header to the source (prevent a couple of static members to be externally unresolved)
- Use the AreAllSignalsBlocked() method instead of the static fgAllSignalsBlocked (prevent it to be externally unresolved)
- Comment out inline TString operator==() to fix the compiler error C2593: 'operator ==' is ambiguous (!!!)
- Implement a working dlsym function
- Remove some obsolete code