Revert "[cxxmodules] Finish the revert in root-project/root@533dd5e50d7"
This reverts commit 3854aa142b82202d36d066ad9ce80f57a00f8276.
It fixes:
"While building module 'Cling_Interpreter' imported from /.../root/core/metacling/src/TClingCallbacks.h:12:
In file included from <module-includes>:11:

/.../root/interpreter/cling/include/cling/Interpreter/DynamicLookupRuntimeUniverse.h:13:2: error: "This file must not be included by compiled programs."

 ^
While building module 'Cling_Interpreter' imported from /.../root/core/metacling/src/TClingCallbacks.h:12:
In file included from <module-includes>:17:"