[RF] Fix in `pythonize_roofit_class` for use with Python 2
The docstring of an instancemethod can't be mutated in Python 2, so the
underlying function has to be obtained first via the `__func__`
attribute.

The original warning:
```
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable
```