[Python][roottest] Don't rely on `__name__` attribute for template test
The regression test for template arguments in namespaces uses the
`__name__` attribute of the template instance as a witness that the
instantiation succeeded. However, this will cause problems when we
update the pretty-printing in cppyy to rightfully include template
arguments:
```txt
======================================================================
FAIL: Test name resolution of template with namespace parameter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rembserj/code/root/root_src/roottest/python/regression/PyROOT_regressiontests.py", line 232, in test1TemplateWithNamespaceParameter
    self.assertEqual( LoKi.Constant( rcp ).__name__, 'Constant<%s>' % rcp )
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'Constant<const Particle *>' != 'Constant<const LHCb::Particle*>'
- Constant<const Particle *>
?                        -
+ Constant<const LHCb::Particle*>
?                ++++++
```

The solution to this problem that this commit suggests is to avoid
string matching in the test, moving the burden to checking if the
template instantiation succeeded to well-defined C++.