Readd support in ClassDef for classes with same name as data member.
For example:

class Rho: public TObject
{
   public:
   Float_t Rho; // rho energy density
   Float_t Edges[2]; // pseudorapidity range edges

   ClassDef(Rho, 1)
};

This leads to a compilation error when doing

  THashConsistencyHolder<name>

and lead to

 error: template argument for template type parameter must be a type

because in that context the data member hid the class name
So we now do

  THashConsistencyHolder<decltype(*this)>