Revert "[cxxmodules] Add more bits headers to fix module merging issues."
This reverts commit 90ffa89ae46b48c634547d6abd861a524a5d27c7.
It causes build failures on GCC 12.2.1 / c++17 with

```
[ 70%] Generating G__Core.cxx, ../lib/Core.pcm
In file included from input_line_7:111:
/home/linev/build/webgui/include/ROOT/RDirectoryEntry.hxx:31:33: error: missing '#include <bits/chrono.h>'; 'system_clock' must be declared before it is used
   using clock_t = std::chrono::system_clock;
                                ^
/usr/include/c++/12/bits/chrono.h:1110:12: note: declaration here is not visible
    struct system_clock
           ^
In module 'std' imported from input_line_1:1:
/usr/include/c++/12/bits/move.h:204:11: error: missing '#include <bits/chrono.h>'; 'time_point' must be defined before it is used
      _Tp __tmp = _GLIBCXX_MOVE(__a);
          ^
/home/linev/build/webgui/include/ROOT/RDirectoryEntry.hxx:89:4: note: in instantiation of function template specialization 'std::swap<std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<long, std::ratio<1, 1000000000>>>>' requested here
   swap(fDate, other.fDate);
   ^
/usr/include/c++/12/bits/chrono.h:856:14: note: definition here is not reachable
      struct time_point
```