[cxxmodules] Add stdlib.h to libc modulemap.
We currently get the error below from stdlib.h as we have problems merging
these special declarations with GCC annotations. We can't add stdlib.h to
the normal libc module as this would cause a dependency cycle between the
builtin modules of clang and libc, but having this as a standalone module
seems to work for me.

```
In file included from input_line_12:18:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/BasicFunctionGradient.h:13:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/MnMatrix.h:31:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/LASymMatrix.h:24:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/StackAllocator.h:28:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:75:
In file included from /home/teemperor/root/dbg-build/etc/cling/lib/clang/5.0.0/include/stdlib.h:8:
/usr/include/stdlib.h:742:8: error: reference to 'lldiv_t' is ambiguous
extern lldiv_t lldiv (long long int __numer,
       ^
/usr/include/stdlib.h:81:5: note: candidate found by name lookup is 'lldiv_t'
  } lldiv_t;
    ^
/usr/include/stdlib.h:81:5: note: candidate found by name lookup is 'lldiv_t'
  } lldiv_t;
    ^
In file included from input_line_12:18:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/BasicFunctionGradient.h:13:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/MnMatrix.h:31:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/LASymMatrix.h:24:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/StackAllocator.h:28:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:75:
In file included from /home/teemperor/root/dbg-build/etc/cling/lib/clang/5.0.0/include/stdlib.h:8:
/usr/include/stdlib.h:742:16: error: functions that differ only in their return type cannot be overloaded
extern lldiv_t lldiv (long long int __numer,
       ~~~~~~~ ^
/usr/include/stdlib.h:742:16: note: previous declaration is here
extern lldiv_t lldiv (long long int __numer,
       ~~~~~~~ ^
In file included from input_line_12:18:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/BasicFunctionGradient.h:13:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/MnMatrix.h:31:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/LASymMatrix.h:24:
In file included from /home/teemperor/root/dbg-build/include/Minuit2/StackAllocator.h:28:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:194:11: error: reference to 'lldiv_t' is ambiguous
  using ::lldiv_t;
          ^
/usr/include/stdlib.h:81:5: note: candidate found by name lookup is 'lldiv_t'
  } lldiv_t;
    ^
/usr/include/stdlib.h:81:5: note: candidate found by name lookup is 'lldiv_t'
  } lldiv_t;
    ^
``