[rootfitcore] Fix ambig op== in RooNormSetCache:
With C++20 we get:
include/RooNormSetCache.h:70:53: error: use of overloaded operator '==' is ambiguous (with operand types 'const RooNormSetCache::Pair::Value_t' (aka 'const unsigned long') and 'const UniqueId<RooArgSet>')
    if (_pairToIdx.end() != it && it->first.first() == RooFit::getUniqueId(set1))
                                  ~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
include/RooFit/UniqueId.h:61:9: note: candidate function (with reversed parameter order)
   bool operator==(UniqueId const &other) const { return _val == other._val; }
        ^
include/RooNormSetCache.h:70:53: note: built-in candidate operator==(unsigned long, unsigned long)
    if (_pairToIdx.end() != it && it->first.first() == RooFit::getUniqueId(set1))
                                                    ^

(cherry picked from commit 38fa29b767736f0fc1e7ffad160b489d0ab13b8f)