Fix compilation error in genreflex dictionary.
When specifying the classname with the :: prefix, we get the error:

classVersion_rflx.cpp:212:1: error: ‘NoIO’ in ‘atomic_TClass_ptr {aka struct std::atomic<TClass*>}’ does not name a type
atomic_TClass_ptr ::NoIO::fgIsA(0);
                  ^

so we ommit the prefix.