Close files before deleting them in TContext tutorial
The TFile objects need to be closed before the ROOT files can be
deleted. Otherwise, we get errors such as these on Windows 10:

```
Traceback (most recent call last):
  File "C:/build/night/LABEL/windows10/SPEC/default/V/master/root/tutorials/pyroot/pyroot006_tcontext_context_manager.py", line 56, in <module>
    os.remove("pyroot006_file_{}.root".format(i))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pyroot006_file_1.root'
CMake Error at C:/build/night/LABEL/windows10/SPEC/default/V/master/build/RootTestDriver.cmake:227 (message):
  error code: 1
```