[ci] Remove `--shm-size=1g -m 16`:
I suspect that this is the cause of the error:
```
Resource limits are not supported and ignored on cgroups V1 rootless systems
  aaa674cabd09a8ff746c97b6c9b065865428b74ddcbcbe54a9892fc3c47d7407
  /bin/docker start aaa674cabd09a8ff746c97b6c9b065865428b74ddcbcbe54a9892fc3c47d7407
  Error: OCI runtime error: unable to start container "aaa674cabd09a8ff746c97b6c9b065865428b74ddcbcbe54a9892fc3c47d7407": runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: cannot set memory limit: container could not join or create cgroup
  Error: Docker start fail with exit code 125
```

(cherry picked from commit 1e3e8e178ee439163001d615545eba2391cbab33)