[roofitcore] Fix ambig op!= in RooAddPdf:
With C++20 we get
```
roofit/roofitcore/src/RooAddPdf.cxx: In member function ‘std::pair<const RooArgSet*, AddCacheElem*> RooAddPdf::getNormAndCache(const RooArgSet*) const’:
roofit/roofitcore/src/RooAddPdf.cxx:436:32: error: ambiguous overload for ‘operator!=’ (operand types are ‘const RooFit::UniqueId<RooArgSet>’ and ‘RooFit::UniqueId<RooArgSet>::Value_t’ {aka ‘long unsigned int’})
  436 |     } else if(nset->uniqueId() != _idOfLastUsedNormSet) {
      |               ~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~
      |                             |     |
      |                             |     RooFit::UniqueId<RooArgSet>::Value_t {aka long unsigned int}
      |                             const RooFit::UniqueId<RooArgSet>
```

(cherry picked from commit 91dd45bd1520b253863346ac27dca209afc76405)