Prefer system pytest if that is installed
If the local pytest module is enabled unconditionally, the local
and system pytest modules conflict with each other. In that case,
it is better to prefer using the system installed package only.
Also, the option "--minimal=yes" is not there anymore, so it was
removed. On my machine, for instance, I see the this error:

  File "/home/amadio/src/roottest/python/pytest/_pytest/core.py", line 177,
  in consider_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/amadio/build/root/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/usr/lib64/python3.6/site-packages/pytest_timeout.py", line 36, in <module>
    @pytest.hookimpl
AttributeError: module 'pytest' has no attribute 'hookimpl'