[windows] Fix compilation error with VS 2019
Fix the following error with Visual Studio 2019:
error C2440: 'initializing': cannot convert from 'int' to 'std::byte'