Fix compilation errors with the `/permissive-` compiler flag on Windo… (#9613)
* Fix compilation errors with the `/permissive-` compiler flag on Windows. Resolves #9607

Fix the following compilation errors when using the `/permissive-` compiler flag:
```
  hist\hist\inc\TF1.h(463,1): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      hist\hist\inc\TF1.h(463,1): message : could be 'TString'
      hist\hist\inc\TF1.h(463,1): message : or       'const char *'

  hist\hist\src\TH1.cxx(3128,91): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      hist\hist\src\TH1.cxx(3128,91): message : could be 'TString'
      hist\hist\src\TH1.cxx(3128,91): message : or       'const char *'

  gui\gui\src\TGFileDialog.cxx(390,53): error C2445: result type of conditional expression is ambiguous: types 'TString' and 'const char [1]' can be converted to multiple common types
      gui\gui\src\TGFileDialog.cxx(390,53): message : could be 'TString'
      gui\gui\src\TGFileDialog.cxx(390,53): message : or       'const char *'

  graf2d\win32gdk\src\TGWin32.cxx(2690,47): error C2664: 'void gdk_gc_set_clip_mask(GdkGC *,GdkBitmap *)': cannot convert argument 2 from 'const unsigned long' to 'GdkBitmap *'
  graf2d\win32gdk\src\TGWin32.cxx(3055,44): error C2664: 'void gdk_gc_set_clip_mask(GdkGC *,GdkBitmap *)': cannot convert argument 2 from 'const unsigned long' to 'GdkBitmap *'
```

* Update gui/gui/src/TGFileDialog.cxx

Co-authored-by: Philippe Canal <pcanal@fnal.gov>

* Update hist/hist/inc/TF1.h

Co-authored-by: Philippe Canal <pcanal@fnal.gov>

* Update hist/hist/src/TH1.cxx

Co-authored-by: Philippe Canal <pcanal@fnal.gov>

* Code formatting

* Formatting

Co-authored-by: Philippe Canal <pcanal@fnal.gov>