[modulemap] bits/chrono.h exists already with C++11:
It is needed for C++11 support of #include <chrono>. Failures:
```
Processing /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C...
In file included from input_line_10:1:
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C:55:51: error: no member named 'duration' in namespace 'std::chrono'
         std::this_thread::sleep_for(std::chrono::duration<double, std::nano>(500));
                                     ~~~~~~~~~~~~~^
```

and

```
root [11] #include <bits/chrono.h>
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:432:10: error: module 'std.bits/chrono.h' requires feature 'cplusplus17'
  module "bits/chrono.h" [optional] {
         ^
ROOT_prompt_11:1:10: note: submodule of top-level module 'std' implicitly imported here
         ^
```

(cherry picked from commit b0f0a83813027c0493eeb87d27555b100614c2b9)