[PyROOT] For MacOs12 with soversion, try to load libcppyy_backend with absolute path
The reason for this fix is that, on MacOS12 with soversion enabled, loading e.g.
libcppyy_backend3_8.so does not work even if LD_LIBRARY_PATH and PYTHONPATH
are properly set. The error is:

OSError: dlopen(libcppyy_backend3_8.so, 0x0006): tried: 'libcppyy_backend3_8.so'
(relative path not allowed in hardened program), '/usr/lib/libcppyy_backend3_8.so'
(no such file)

An alternative that would also work would be to load the library with no path
and its fully versioned name (e.g. libcppyy_backend3_8.6.27.so). The problem
of that solution is that, at the moment of loading libcppyy_backend, cppyy is
not fully initialized and lookups can't be done yet, so we can't get the ROOT
version via gROOT.GetVersion().