This patch contains fixes to rootcint by Victor and Mathieu de Naurois. From Victor Changes in function ShortTypeName
From Mathieu
fix to avoid error messages like:
ERROR: This version of ROOT requires the presence of an actual
declaration of:
   TBuffer &operator>>(TBuffer
&,Sash::TelescopeMonitorBase2<Sash::PixelHVTempMonitor,Sash::DrawerHVTempMonitor>
*&);
Class Sash::TelescopeMonitorBase<Sash::PixelScalerMonitor>: Do not
generate operator>>()
ERROR: This version of ROOT requires the presence of an actual
declaration of:
   TBuffer &operator>>(TBuffer
The fix suppress the test on the operator >> being present for templated classes.


git-svn-id: http://root.cern.ch/svn/root/trunk@4669 27541ba8-7e3a-0410-8455-c3a389f83636