Do not include VecCore as system for test-veccore
This breaks linking of the test with the error below:

Scanning dependencies of target test-veccore
[100%] Building CXX object test/CMakeFiles/test-veccore.dir/test-veccore.cxx.o
In file included from /usr/include/VecCore/Limits.h:9:0,
                 from /usr/include/VecCore/Backend/Implementation.h:5,
                 from /usr/include/VecCore/VecCore:12,
                 from /home/amadio/src/root/test/test-veccore.cxx:2:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include/g++-v7/cmath:45:15:
	fatal error: math.h: No such file or directory
 #include_next <math.h>
               ^~~~~~~~