[core] Fix `CompressionSettings()` declaration
Fix typo in `CompressionSettings()` function declaration to match
definition in Compression.cxx. This typo caused the following to fail:
```
root [0] auto c = ROOT::RCompressionSetting::EAlgorithm::kZSTD;
root [1] CompressionSettings(c, 5);
input_line_10:2:3: error: no matching function for call to 'CompressionSettings'
 (CompressionSettings(((*(enum ROOT::RCompressionSetting::EAlgorithm::EValues*)0x7f02285f4010)), 5))
  ^~~~~~~~~~~~~~~~~~~
/home/jalopezg/_build/include/Compression.h:124:5: note: candidate function not viable: no known conversion from 'enum ROOT::RCompressionSetting::EAlgorithm::EValues' to 'RCompressionSetting::EAlgorithm' for 1st argument
int CompressionSettings(RCompressionSetting::EAlgorithm algorithm, int compressionLevel);
    ^
/home/jalopezg/_build/include/Compression.h:126:5: note: candidate function not viable: no known conversion from 'enum ROOT::RCompressionSetting::EAlgorithm::EValues' to 'ROOT::ECompressionAlgorithm' for 1st argument
int CompressionSettings(ROOT::ECompressionAlgorithm algorithm, int compressionLevel);
    ^
```