Fix compilation errors on Windows
 - Fix error C2057: expected constant expression in several array declarations
 - Outline (move from header to source) the IsCandleScaled() and IsViolinScaled() to export them from DLL
 - In fontembedps.cxx, replace unsupported memmem() function by std::search()