When autoloading from the interpreter, we also need to autoparse.
This is especially true for TClingCallbacks::InclusionDirective and parsing a header might lead to the
indirect request for autoparsing a related type which could lead to the parsing of header files that
requires types declared in the top most header (the one that induces the autoparsing) but this fails
because the 2nd inclusion of the header is ineffective (code guard are respected) but the 1st inclusion is
not finish.

This fixes root.exe -b -l -q stressShapes which lead to something like:

In file included from input_line_234:50:
/local2/pcanal/root_working/nightly/trunk/root/include/TGeoPatternFinder.h:89:65: error: member access into incomplete type 'TGeoVolume'
   TGeoNode           *GetNodeOffset(Int_t idiv) {return fVolume->GetNode(fDivIndex+idiv);}
                                                                ^