Revert "Mark unimplemented new() "throw()" as they return nullptr."
This reverts commit ecbb242200e9a3a57346e0a9386199a6c0431d27.
The commit caused the compilation error:
core/newdelete/src/NewDelete.cxx:214:7: error: exception specification in declaration does not match previous declaration
void *operator new(size_t /*size*/, std::align_val_t /*al*/) throw()
      ^
/cvmfs/sft.cern.ch/lcg/contrib/gcc/7binutils/x86_64-centos7/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/new:143:7: note: previous declaration is here
void* operator new(std::size_t, std::align_val_t)
      ^