Fix assignment operators.
Fixes clang-tidy readability-deleted-default:
error: move assignment operator is explicitly defaulted but implicitly
deleted, probably because a base class or a non-static data member is
not assignable, e.g. because the latter is marked 'const'; definition
can either be removed or explicitly deleted

   TAxisBase &operator=(TAxisBase &&) = default;
   ^

(same for copy assignment)