Require at least GCC 5.2.0 to enable Vc in ROOT
Vc has ABI issues with GCC 4.x (needs -fabi-version=6 or 0 to work),
and at least with GCC 4.9.3, Vc triggers the static asserts shown below:

include/Vc/common/simdize.h:758:1: error: static assertion failed:
is_constructible_with_double_brace<int> does not work as expected

include/Vc/common/simdize.h:762:1: error: static assertion failed:
is_constructible_with_double_brace<tuple> does not work as expected

include/Vc/common/simdize.h:765:1: error: static assertion failed:
is_constructible_with_double_brace<array> does not work as expected

Reference: http://cdash.cern.ch/viewBuildError.php?buildid=383616