Fix warning about implicit function declaration in CivetWeb
Using pthread_setname_np requires a #define _GNU_SOURCE before including
pthread.h, or it will cause warnings about implicit function declaration:

net/http/civetweb/civetweb.c:2701:8: warning:
 implicit declaration of function 'pthread_setname_np' is invalid in C99
         (void)pthread_setname_np(pthread_self(), threadName);
               ^