Add missing `onnx` to requirements.txt
The `onnx` Python module is required for TMVA SOFIE.
Adding this will fix the test failures of
`gtest-tmva-sofie-test-TestSofieModels`:

```
  [ RUN      ] SOFIE.Linear_B1
  using batch-size = 1 input dim = 10 nlayers = 4
  input data torch.Size([1, 10])
  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
  Traceback (most recent call last):
    File "/py-venv/ROOT-CI/lib/python3.8/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 221, in _add_onnxscript_fn
      import onnx
  ModuleNotFoundError: No module named 'onnx'
```