[io] Don't use `R__ALWAYS_INLINE` In TBufferJSON
The `R__ALWAYS_INLINE` macro was introduced by commit 2f0f8b9 in
TBufferJSON. However, it breaks the build with GCC and the `-Og` flag,
for debug-compatible optimizations:

```txt
In member function ‘void TBufferJSON::JsonWriteFastArray(const T*, Int_t, const char*, void (TBufferJSON::*)(const T*, Int_t, const char*)) [with T = bool]’,
    inlined from ‘virtual void TBufferJSON::WriteFastArray(const Bool_t*, Int_t)’ at /home/rembserj/spaces/master-debug/root/src/root/io/io/src/TBufferJSON.cxx:3296:22:
/home/rembserj/spaces/master-debug/root/src/root/io/io/src/TBufferJSON.cxx:3034:23: error: inlining failed in call to ‘always_inline’ ‘void TBufferJSON::JsonWriteArrayCompress(const T*, Int_t, const char*) [with T = bool]’: function not considered for inlining
 3034 | R__ALWAYS_INLINE void TBufferJSON::JsonWriteArrayCompress(const T *vname, Int_t arrsize, const char *typname)
```

Libraries other than ROOT have also encountered similar problems:
https://github.com/Cyan4973/xxHash/pull/804

The `R__ALWAYS_INLINE` macro is probably not necessary for these
templated functions, because the compiler figures out itself whether
it's worth to inline the templated functions or not.