[DF] Fix potential compilation error on mac1012, XCode9
v6.16 was not affected (yet) but this commit synchronizes it
with the status of current master and defends it against future
problems of this kind.

Link to compilation error:
https://epsft-jenkins.cern.ch/view/ROOT%20Nightly/job/root-nightly-master/1977/LABEL=mac1012,SPEC=noimt/parsed_console/

The error is due to a bug in clang3.5, reproducible in isolation:
https://godbolt.org/z/jtYXv6

The workaround is to avoid specifying the template parameters of a
template base class -- the full type is injected in the derived class
anyway (thanks Axel!).