Fix string_view compilation errors on Windows
 - enclose min() and max() in parentheses to prevent the following compilation errors (min and max are defined as macros in Visual Studio):
     error C2589: '(' : illegal token on right side of '::'
     error C2059: syntax error : '::'
 - implement the basic_string_view operator == (for const char *) (was somehow not resolved by Visual Studio). Thanks Axel for fixing it