[CPyCppyy] Correctly propagate template argument name errors
In case the `Utility::ConstructTemplateArgs()` method fails to create
the C++ template names, it sets a useful Python exception that is
unfortunately not propagated, because the calling code in
`TemplateProxy.cxx` is ignoring it. This is fixed in this commit.

The place where the error is set is also moved from
`Utility::ConstructTemplateArgs()` to the actual implementation:
`AddTypeName()`. This means the error is set by the function that
actually has the context of the error, which is conceptually cleaner and
will allow us also to set more detailed errors for different failure
modes of `AddTypeName()`.

A unit test is also implemented.

Demo code:
```python
import cppyy

cppyy.cppdef("""

template<class T>
class Foo {};

template<class T, class Y=void>
auto make_foo () { return Foo<T>{}; }

template<class T, class Y=void>
auto make_foo (T x) { return Foo<T>{}; }

""")

cppyy.gbl.make_foo[set(), list()]()

```

Before:
```
    cppyy.gbl.make_foo[set(), list()]()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: Could not find "make_foo" (set cppyy.set_debug() for C++ errors):
  Template method resolution failed:
  Failed to instantiate "make_foo()"
  Failed to instantiate "make_foo()"
```

After:
```
    cppyy.gbl.make_foo[set(), list()]()
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: could not construct C++ name from template argument set()
```

Note: this work is orthogonal to the rebase of `cppyy` on CppInterOp.