Disable Numba tests on Windows
Disable the numba tests which are raising this error on Windows:
OSError: dlopen(None) cannot work on Windows for Python 3 (see http://bugs.python.org/issue23606)