[PyROOT] Replace assertEquals (removed in Python 3.12) with assertEqual
The deprecated alias assertEquals has been removed in Python 3.12:
https://docs.python.org/3.12/whatsnew/3.12.html#removed

The removal causes tests to fail with errors like the one below:

Traceback (most recent call last):
  File "root/bindings/pyroot/pythonizations/test/tclass_dynamiccast.py",
       line 22, in test_dynamiccast
    self.assertEquals(type(o_upcast), TObject)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'TClassDynamicCast' object has no attribute 'assertEquals'.
                Did you mean: 'assertEqual'?