[RDF] Fix compilation of dataframe_nodes test on Windows
dataframe_nodes.cxx(97): error C3493: 'nBinsExpected' cannot be
implicitly captured because no default capture mode has been specified