Revert "Address ROOT-9114 (Issues with dictionary's enum forward decl)"
This reverts commit 59c69dc2ce449eff8cabcf73405b04b07aaf9eb3.

This commit leads to the following type of failures:

I rebuilt ROOT6 CMSSW IB based on new commit but now I see compilation errors [a] while running edmCheckClassTransients

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_ROOT6_X_2017-11-18-1100/DataFormats/BTauReco

In file included from CMSSW_10_0_ROOT6_X_2017-11-18-1100/src/DataFormats/BTauReco/interface/TrackIPTagInfo.h:7:
  CMSSW_10_0_ROOT6_X_2017-11-18-1100/src/DataFormats/BTauReco/interface/IPTagInfo.h:179:24: error: no member named 'trackMomentum' in namespace 'reco::btau'
      vars.insert(btau::trackMomentum, trackMag, true);
                 ~~~~~~^
  CMSSW_10_0_ROOT6_X_2017-11-18-1100/src/DataFormats/BTauReco/interface/IPTagInfo.h:180:24: error: no member named 'trackEta' in namespace 'reco::btau'
      vars.insert(btau::trackEta, trackMom.Eta(), true);
                 ~~~~~~^
  CMSSW_10_0_ROOT6_X_2017-11-18-1100/src/DataFormats/BTauReco/interface/IPTagInfo.h:181:24: error: no member named 'trackEtaRel' in namespace 'reco::btau'
      vars.insert(btau::trackEtaRel, reco::btau::etaRel(jetDir, trackMom), true);