Fix classic build error for missing TypeTraits.hxx header
Seen at: http://cdash.cern.ch/viewBuildError.php?buildid=370038

include/ROOT/TDFActionHelpers.hxx:15:31:
  fatal error: ROOT/TypeTraits.hxx: No such file or directory
  #include "ROOT/TypeTraits.hxx"
                               ^
compilation terminated.
In file included from include/ROOT/TDFInterface.hxx:14:0,
                 from /.../root/tree/treeplayer/src/TDFInterface.cxx