[tmva][sofie] Only one statement per line in `PyRunString`
This follows up on 29b8e84b3d0ff1d0f, fixing a syntax error:
```txt
Python error message:
  File "<string>", line 1
    import tensorflow.keras as keras
                                    ^
SyntaxError: multiple statements found while compiling a single statement
```

(cherry picked from commit 7fa8c6d8cf04c2fdff85edaab98ba904a5e196a7)