Add missing destructor.
This fixes the error/warning:

relations_load_C_ACLiC_dict.cxx:425:7: error: delete called on '::IInterface' that is abstract but has non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
      delete ((::IInterface*)p);
      ^