[build] Update builtin UNURAN to 1.11.0
Update builtin to latest version, including a crucial fix introduced by
commit
https://github.com/unuran/unuran/commit/8cb1dc4f1330492c3976d099270ff271bfe38f35
which avoids the following build error visible with a GCC 15 build:
```
In file included from pinv.c:553:
pinv_newton.ch: In function '_unur_pinv_newton_maxerror':
pinv_newton.ch:581:9: error: too many arguments to function '_unur_pinv_cubic_hermite_is_monotone'; expected 0, have 4
  581 |       ! _unur_pinv_cubic_hermite_is_monotone(gen,ui,zi,xval))
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~
pinv.c:443:12: note: declared here
  443 | static int _unur_pinv_cubic_hermite_is_monotone();
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pinv_newton.ch: At top level:
pinv_newton.ch:669:1: error: conflicting types for '_unur_pinv_cubic_hermite_is_monotone'; have 'int(struct unur_gen *, double *, double *, double *)'
  669 | _unur_pinv_cubic_hermite_is_monotone(struct unur_gen *gen, double *ui, double *zi, double *xval)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pinv.c:443:12: note: previous declaration of '_unur_pinv_cubic_hermite_is_monotone' with type 'int(void)'
  443 | static int _unur_pinv_cubic_hermite_is_monotone();
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This also removes the need for a patch of the LCG build system
https://gitlab.cern.ch/sft/lcgcmake/-/commit/7c93a4a2747d01333e739f67f43f7cd8c607dc34