[core] Add missing includes
This will fix build errors like:
error: declaration of 'type_info' must be imported from module 'std.std_typeinfo' before it is required