Fix MSVC compilation error C2065: 'thread_local' : undeclared identifier
Cannot use the proper 'static __declspec(thread)' definition, since it gives the following errors:
error C2483: 'includeName' : object with constructor or destructor cannot be declared 'thread'