[trint] Correctly handle line continuation after '\'
To have better diagnostics, `TRint::ProcessLineNr()` prepends a
`#line 1 "ROOT_prompt_xxx"` PP directive to each input line.  However, this
causes problems if the previous line is continued with '\', e.g.
```
root [0] #define m(x) printf("%s", \
root (cont'ed, cancel with .@) [1]x);
ROOT_prompt_0:2:2: error: '#' is not followed by a macro parameter
 ^
ROOT_prompt_0:3:1: error: use of undeclared identifier 'x'
x);
^
```
This patch fixes issue #8762.