Update gtest to latest version 1.10.0 (#5228)
* Update gtest to latest version 1.10.0

More info: https://github.com/google/googletest/releases/tag/release-1.10.0

* Adjust cmake variables to be used by Ninja of build byproducts

* Replace deprecated functions for googletest 1.10 release

* Add missing gtest_main target

* Fix locations for gtest and gtest_main targets

* Update CMake configuration for gtest tests

Tests were failing with next error: /usr/bin/ld: ../../../googletest-prefix/src/googletest-build/lib/libgtest_main.a(gtest_main.cc.o): in function testing::InitGoogleTest(int*, char**)
/usr/bin/ld: gtest_main.cc:(.text.startup+0x2f): undefined reference to testing::UnitTest::Run()

* Patch by Bertrand Bellenot: Update build configuration for Windows

* We build googletest in Release mode (for Debug names of libraries should be different and require special treatment)

* [formating] Add EOL in CMakeLists.txt