[CI] Disable `pythia8` on alma9 gcc configuration
The new Pythia version 8.313 is missing to add the `inline` keyword to
some functions in header files, resulting in linker errors like below.

This commit suggest to disable the Pythia8 interfaces until this
regression is fixed upstream.

```
/usr/bin/ld: CMakeFiles/EGPythia8.dir/src/TPythia8.cxx.o: in function `TPythia8::ReadString(char const*) const':
/github/home/ROOT-CI/src/montecarlo/pythia8/src/TPythia8.cxx:302: undefined reference to `Pythia8::Pythia::readString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)'
/usr/bin/ld: CMakeFiles/EGPythia8.dir/src/TPythia8.cxx.o: in function `TPythia8::ReadConfigFile(char const*) const':
/github/home/ROOT-CI/src/montecarlo/pythia8/src/TPythia8.cxx:310: undefined reference to `Pythia8::Pythia::readFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)'
/usr/bin/ld: CMakeFiles/EGPythia8.dir/src/TPythia8Decayer.cxx.o: in function `TPythia8Decayer::TPythia8Decayer()':
/github/home/ROOT-CI/src/montecarlo/pythia8/src/TPythia8Decayer.cxx:33: undefined reference to `Pythia8::Pythia::readString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [montecarlo/pythia8/CMakeFiles/EGPythia8.dir/build.make:131: lib/libEGPythia8.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:58046: montecarlo/pythia8/CMakeFiles/EGPythia8.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```