Alleviate the symptoms of ROOT-7181.
The underlying problem is still there and shown below.  The cause is that
when GetNormalizedName is run with autoloading disabled, it can lead to the
premature instantiation of partially specialized templates.

  .x /local2/pcanal/root_working/test/2015-04-attila/root6DVDictLoading/RootCore/scripts/load_packages.C
  TFile *_file0 = TFile::Open("../AOD.01597980._000098.pool.root.1")
  std::string normalizedName;
  int oldAutoloadVal = gInterpreter->SetClassAutoloading(false);
  TClassEdit::GetNormalizedName(normalizedName, "SG::AuxTypeVectorFactory<ElementLink<DataVector<xAOD::Photon_v1> > >")
  gInterpreter->SetClassAutoloading(oldAutoloadVal)
  TClass::GetClass("ElementLink<DataVector<xAOD::Photon_v1> >")->GetClassInfo()
...
In file included from input_line_143:60:
In file included from .../RootCore/include/xAODEgamma/PhotonContainer.h:8:
/local2/pcanal/root_working/test/2015-04-attila/root6DVDictLoading/RootCore/include/xAODEgamma/versions/PhotonContainer_v1.h:14:1: error: explicit specialization of 'DataVectorBase<xAOD::Photon_v1>' after instantiation
DATAVECTOR_BASE( xAOD::Photon_v1, xAOD::Egamma_v1 );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../RootCore/include/AthContainers/DataVector.h:612:43: note: expanded from macro 'DATAVECTOR_BASE'
#define DATAVECTOR_BASE(T, BASE)          \
^
.../RootCore/include/AthContainers/DataVector.h:622:20: note: expanded from macro '\
DATAVECTOR_BASE_FWD'
template <> struct DataVectorBase<T>      \
^~~~~~~~~~~~~~~~~
.../RootCore/include/AthContainers/DataVector.h:718:42: note: implicit instantiation first required here
template <class T, class BASE = typename DataVectorBase<T>::Base>
^
Error in <TInterpreter::AutoParse>: Error parsing payload code for class DataVector<xAOD::Photon_v1> with content: