[Math] Fix variable length array warning in RMinimzer
Fix the following warning:

```txt
math/rtools/src/RMinimizer.cxx:28:19: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   28 |          double z[size];
      |                   ^~~~
math/rtools/src/RMinimizer.cxx:28:19: note: read of non-const variable 'size' is not allowed in a constant expression
math/rtools/src/RMinimizer.cxx:26:23: note: declared here
   26 |          unsigned int size = y.GetNoElements();
      |                       ^
```

(cherry picked from commit 754ab646a9292634d9eb640516cc828f19d0896f)