Remove `define const` hack in ifparser.h
Defining const as empty and then including the standard headers after
`ifparser.h` in `ifparser.c` results in several compiler errors on my
system when I compile with Clang 21 using the glibc fortify wrappers
(see below).

At this point, I think ROOT is built only with C compilers that support
`const` so we don't need the hack of defining it as an empty
preprocessor macro anymore.

```txt
[275/3601] Building C object misc/rmkdepend/CMakeFiles/rmkdepend.dir/ifparser.c.o
FAILED: [code=1] misc/rmkdepend/CMakeFiles/rmkdepend.dir/ifparser.c.o
/nix/store/habs4w5zka28717s5yys25i7vrd5766b-ccache-4.12.3/bin/ccache /nix/store/6n5r46icm0bl55s9p5z2zgcv93m39r5l-clang-wrapper-21.1.8/bin/clang   -fno-omit-frame-pointer -fcolor-diagnostics -Qunused-arguments -pipe -Wall -W -pthread -O2 -g -DNDEBUG -MD -MT misc/rmkdepend/CMakeFiles/rmkdepend.dir/ifparser.c.o -MF misc/rmkdepend/CMakeFiles/rmkdepend.dir/ifparser.c.o.d -o misc/rmkdepend/CMakeFiles/rmkdepend.dir/ifparser.c.o -c /home/rembserj/code/root/root_src/misc/rmkdepend/ifparser.c
In file included from /home/rembserj/code/root/root_src/misc/rmkdepend/ifparser.c:65:
In file included from /nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/stdlib.h:1165:
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/stdlib.h:38:54: error: pass_object_size attribute only applies to constant pointer arguments
   38 |                  __fortify_clang_overload_arg (char *, __restrict, __resolved)))
      |                                                                    ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/stdlib.h:73:43: error: pass_object_size attribute only applies to constant pointer arguments
   73 |                  __fortify_clang_overload_arg (char *, ,__buf),
      |                                                         ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/stdlib.h:91:55: error: pass_object_size attribute only applies to constant pointer arguments
   91 | __NTH (wctomb (__fortify_clang_overload_arg (char *, ,__s), wchar_t __wchar))
      |                                                       ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/stdlib.h:129:71: error: pass_object_size attribute only applies to constant pointer arguments
  129 | __NTH (mbstowcs (__fortify_clang_overload_arg (wchar_t *, __restrict, __dst),
      |                                                                       ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/stdlib.h:159:68: error: pass_object_size attribute only applies to constant pointer arguments
  159 | __NTH (wcstombs (__fortify_clang_overload_arg (char *, __restrict, __dst),
      |                                                                    ^
In file included from /home/rembserj/code/root/root_src/misc/rmkdepend/ifparser.c:66:
In file included from /nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/string.h:548:
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:77:66: error: pass_object_size attribute only applies to constant pointer arguments
   77 | __NTH (strcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                  ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:86:66: error: pass_object_size attribute only applies to constant pointer arguments
   86 | __NTH (stpcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                  ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:96:67: error: pass_object_size attribute only applies to constant pointer arguments
   96 | __NTH (strncpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                   ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:107:56: error: pass_object_size attribute only applies to constant pointer arguments
  107 | __NTH (stpncpy (__fortify_clang_overload_arg (char *, ,__dest),
      |                                                        ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:136:66: error: pass_object_size attribute only applies to constant pointer arguments
  136 | __NTH (strcat (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                  ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:145:67: error: pass_object_size attribute only applies to constant pointer arguments
  145 | __NTH (strncat (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                   ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:161:67: error: pass_object_size attribute only applies to constant pointer arguments
  161 | __NTH (strlcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                   ^
/nix/store/rwalsamz4246k8f1zzxa54qx7w3fbzdg-glibc-2.42-47-dev/include/bits/string_fortified.h:179:67: error: pass_object_size attribute only applies to constant pointer arguments
  179 | __NTH (strlcat (__fortify_clang_overload_arg (char *, __restrict, __dest),
      |                                                                   ^
13 errors generated.
```