[tutorials] Remove `main()` function with no return statement
This is to avoid a warning when running the tutorials:
```txt
Processing /github/home/ROOT-CI/src/tutorials/machine_learning/TMVA_SOFIE_GNN_Application.C...
In file included from input_line_10:1:
 ##[error]/github/home/ROOT-CI/src/tutorials/machine_learning/TMVA_SOFIE_GNN_Application.C:14:10: fatal error: 'encoder.hxx' file not found
 #include "encoder.hxx"
         ^~~~~~~~~~~~~
 ##[error]/github/home/ROOT-CI/src/tutorials/machine_learning/TMVA_SOFIE_GNN_Application.C:138:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
```

(cherry picked from commit 50c9227e3b9efd45ee3ee4afe2edfda7e96b873f)