Fix mathtext warnings/errors on Windows
This should fix the warnings with cl.exe and errors with clang_cl.exe as reported in the issue #13091:
With cl.exe:
```
graf2d\mathtext\src\mathtextencode.cxx(353,19): warning C4066: characters beyond first in wide-character constant ignored
```
With clang_cl.exe
```
graf2d\mathtext\src\mathtextencode.cxx(174,33): error: character too large for enclosing character literal type
            default:   _glyph = L'\U0001d538' + (_code[0] - 'A');
```
Note that this PR doesn't make it working, since wchar_t is 16 bit on Windows and 32 bit on Linux and Mac, and to make it working with all possible characters on all platforms, one would need to use `char32_t` everywere, also in `TMathText` and `TLatex`