Revert "Fix memory leak in GetStreamInfoListImpl"
This reverts commit 449650a22816aa100ce2f7d521e7ecb2d9d9199e.
This commit breaks C++11 builds with the following error:

include/ROOT/RMakeUnique.hxx:28:64:
   error: invalid use of array with unspecified bounds