[Math] Replace `STATIC_CHECK` with `static_assert`
As C++11 has now `static_assert`, we can use that now.

The compile-time error messages are also nicer.

For example, here with the old `STATIC_CHECK`:
```txt
testSMatrix.cxx:822:61:   required from here
  822 |    SMatrix<double, 2, 5> tmp2 = A.Sub<SMatrix<double, 2, 5>>(0, 0);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/rembserj/code/root/root_install/include/Math/StaticCheck.h:59:24: error: too many initializers for ‘ROOT::Math::CompileTimeChecker<false>’
   59 |    (void) (ROOT::Math::CompileTimeChecker<(expr) != 0> (&e)); }
      |           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rembserj/code/root/root_install/include/Math/HelperOps.h:466:10: note: in expansion of macro ‘STATIC_CHECK’
  466 |          STATIC_CHECK( D2 <= D4,Smatrix_ncols_too_small);
      |
```

And using `static_assert` with this commit:
```txt
testSMatrix.cxx:822:61:   required from here
  822 |    SMatrix<double, 2, 5> tmp2 = A.Sub<SMatrix<double, 2, 5>>(0, 0);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/rembserj/code/root/root_install/include/Math/HelperOps.h:465:28: error: static assertion failed: Smatrix_ncols_too_small
  465 |          static_assert( D2 <= D4, "Smatrix_ncols_too_small");
      |                         ~~~^~~~~
/home/rembserj/code/root/root_install/include/Math/HelperOps.h:465:28: note: the comparison reduces to ‘(5 <= 4)’
```