Fix compilation error with the `/permissive-` flag on Windows
Fix the following error with the `/permissive-` compiler flag on Windows
```
   gui\webdisplay\src\RWebDisplayHandle.cxx(288,66): error C2440: 'initializing': cannot convert from 'TString' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
```