[df] Ensure proper cleanup of dask connection in tests
The connection object (i.e. a Dask Client wrapping a LocalCluster) created for
running the distributed RDataFrame test suite is now better managed at the end
of the test run.

Sporadically, the following Python error was seen at the end of a perfectly fine
test suite run:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.14/logging/__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
ValueError: I/O operation on closed file.
```

The cause for the error may be due to the fact that pytest is shutting down the
Python process, thus also closing the streams, but some Dask workers may still
be trying to write logging outputs to them.

In general, closing a Client connection but not closing also the attached
cluster can lead to inconsistencies in the target application, as highlighted
e.g. by https://github.com/dask/distributed/issues/1042.

Unfortunately, the interaction between Client, cluster and garbage collection
seems to be neither straightforward nor completely understood even by the Dask
community itself, see for example
https://dask.discourse.group/t/best-practice-for-shutting-down-a-cluster/.