Work around compiler warning about unused type and variables and missing virtual desctructor.
For example:

root/io/evolution/ClassConv.h:37:14: error: private field 't' is not used [-Werror,-Wunused-private-field]
   Typedefed t;

root/io/evolution/versions/lhcb/./DataObject.h:31:23: error: private field 'm_refCount' is not used [-Werror,-Wunused-private-field]
  unsigned long       m_refCount;
                      ^
root/tree/evolution/execMissingCollection_cxx_ACLiC_dict.cxx:314:7: error: delete called on '::MoreNested' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
      delete ((::MoreNested*)p);
      ^